### ISSUE TITLE
【bug】存储文件名都一样

### ISSUE THREAD

**Issue by Xian0Grem** [ChenXu233/nonebot-plugin-safeR18#1]
不知道什么神奇原因,我bot所保存的图片都是一个文件名
![image](https://github.com/user-attachments/assets/b334121e-5ae1-45f6-b39d-69283da9d00c)

**Comment by Xian0Grem** [comment]
一觉醒来又好了,真奇怪

**Comment by Xian0Grem** [comment]
我再次复现了这个bug,我重新部署了个nonebot并安装了本插件后刚运行就出现了重复保存相同文件名的情况
我使用的协议端是napcatqq,抱歉我并没有时间去测试其中原因
貌似是协议端的问题,很玄学,可能我一觉醒来又好了

11-14 00:38:24 [SUCCESS] nonebot | OneBot V11 2329289433 | [message.private.friend]: Message 1790281003 from 2640036416 '[image:summary=,file=000001604e61704361744f6e65426f747c4d736746696c657c317c755f676733486...,sub_type=0,file_id=000001604e61704361744f6e65426f747c4d736746696c657c317c755f676733486...,url=https://multimedia.nt.qq.com.cn/download?appid=1406&fileid=EhSzQwgT...,file_size=465298,file_unique=85b6e2ad53bf05668d1947443f9413f4]'
11-14 00:38:24 [DEBUG] nonebot | Checking for matchers completed
11-14 00:38:24 [DEBUG] nonebot | Running PostProcessors...
11-14 00:38:25 [DEBUG] nonebot_plugin_safeR18 | [[ -0.12060183  -2.4615333   -4.436157    -4.11505     -8.854668
  -23.299541   -23.00012    -24.454433   -24.057884   -23.801119  ]]
11-14 00:38:25 [DEBUG] nonebot_plugin_safeR18 | [-0.12060183 -2.4615333  -4.436157   -4.11505    -8.854668  ]
11-14 00:38:25 [DEBUG] nonebot_plugin_safeR18 | 0
11-14 00:38:25 [INFO] nonebot_plugin_safeR18 | 未发现色图
11-14 00:38:33 [SUCCESS] nonebot | OneBot V11 2329289433 | [message.private.friend]: Message 363233994 from 2640036416 '[image:summary=,file=000001604e61704361744f6e65426f747c4d736746696c657c317c755f676733486...,sub_type=0,file_id=000001604e61704361744f6e65426f747c4d736746696c657c317c755f676733486...,url=https://multimedia.nt.qq.com.cn/download?appid=1406&fileid=EhQ_Xis1...,file_size=270981,file_unique=e2ea66984a2e16fe1648d5fcfe26ccb9]'
11-14 00:38:33 [DEBUG] nonebot | Checking for matchers completed
11-14 00:38:33 [DEBUG] nonebot | Running PostProcessors...
11-14 00:38:34 [DEBUG] nonebot_plugin_safeR18 | [[ -3.8827755  -0.1291898  -9.018371   -2.3011274  -8.009761  -33.797356
  -32.919228  -35.046032  -34.71587   -34.77082  ]]
11-14 00:38:34 [DEBUG] nonebot_plugin_safeR18 | [-3.8827755 -0.1291898 -9.018371  -2.3011274 -8.009761 ]
11-14 00:38:34 [DEBUG] nonebot_plugin_safeR18 | 1
11-14 00:38:34 [INFO] nonebot_plugin_safeR18 | 发现色图！已保存到F:\NoneBot\nonebot_liyu\debug\data\nonebot\data\nonebot_plugin_safeR18\ef72ad57-1004-59f7-9038-804db9a3d4cf.jpg
11-14 00:38:45 [SUCCESS] nonebot | OneBot V11 2329289433 | [message.private.friend]: Message 513284542 from 2640036416 '[image:summary=,file=000001604e61704361744f6e65426f747c4d736746696c657c317c755f676733486...,sub_type=0,file_id=000001604e61704361744f6e65426f747c4d736746696c657c317c755f676733486...,url=https://multimedia.nt.qq.com.cn/download?appid=1406&fileid=EhTfZgFM...,file_size=1044773,file_unique=57325428acac2ea93f0f30c066f9ac18]'
11-14 00:38:45 [DEBUG] nonebot | Checking for matchers completed
11-14 00:38:45 [DEBUG] nonebot | Running PostProcessors...
11-14 00:38:46 [DEBUG] nonebot_plugin_safeR18 | [[ -1.348485   -0.7460769  -3.5319266  -1.5626087  -3.6056044 -10.349701
  -10.00786   -11.301856  -10.6575165 -10.709455 ]]
11-14 00:38:46 [DEBUG] nonebot_plugin_safeR18 | [-1.348485  -0.7460769 -3.5319266 -1.5626087 -3.6056044]
11-14 00:38:46 [DEBUG] nonebot_plugin_safeR18 | 1
11-14 00:38:46 [INFO] nonebot_plugin_safeR18 | 发现色图！已保存到F:\NoneBot\nonebot_liyu\debug\data\nonebot\data\nonebot_plugin_safeR18\ef72ad57-1004-59f7-9038-804db9a3d4cf.jpg
11-14 00:38:49 [DEBUG] nonebot | Running PostProcessors...

**Comment by ChenXu233** [comment]
奇怪了，uuid还能生成一样的？

**Comment by ChenXu233** [comment]
还能复现吗？

**Comment by Xian0Grem** [comment]
无法复现了

**Comment by ChenXu233** [comment]
那就close了（
